// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzamkhsfakswrwlhtjro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6YW1raHNmYWtzd3J3bGh0anJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTY2MDMsImV4cCI6MjA2ODg3MjYwM30.Rpp5Kzekw3w0TpmWp5SbVkw78MVPLZQYerkCFgp-TP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});